### ISSUE TITLE
Working with Automate Schedule

### ISSUE THREAD

**Issue by itreddragon** [automateps/AutomatePS#1]
## Expected Behavior
Connection to the Automate Schedule server using "Connect-AMServer"

## Actual Behavior
I get an "Access Denied" when using the command.

## Steps to Reproduce the Problem

  1. Connect-AMServer -Server SERVER01 -Credential (Get-Credential)
         "Failed to authenticate to server"
  2. Connect-AMServer -Server SERVER01 -Credential (Get-Credential) -Port 8443
         "Failed to authenticate to server"

Does this module work with "Automate Schedule"?

## Specifications

  - AutoMatePS Version: 2.0.1
  - PowerShell Version: 5.1
  - AutoMate Enterprise Version: xx
  - Automate Schedule: R04M021171213

**Comment by davidseibel** [comment]
I'm sorry, this module only works with AutoMate Enterprise, formerly AutoMate BPA.  This does not work with AutoMate Schedule/Skybot.

Thank you
