### ISSUE TITLE
Issue found in Add-AMWorkflowLink.ps1

### ISSUE THREAD

**Issue by sknijn** [automateps/AutomatePS#20]
## Expected Behavior
New-AMWorkflow -Name "Flow01" 
Get-AMWorkflow -Name "Flow01" | Add-AMWorkflowItem -Item (New-AMFileSystemCondition -Name "Share01" -MonitorFolder "\\DC001\01" -FileAdded -Include *.ftpok -UserMode DefaultUser)
Get-AMWorkflow -Name "Flow01" | Add-AMWorkflowItem -Item (New-AMTask -Name "Task01")
Get-AMWorkflow -Name "Flow01" | Add-AMWorkflowLink -SourceConstruct (Get-AMCondition -Name "Share01") -DestinationConstruct (Get-AMTask "Task01")

Results in creating flow with task and file monitor condition

## Actual Behavior
I got an error at $Value=""

## To fix this problem:
I changed $Value=""   into    Clear-Item Variable:Value, except for the first one:         [ValidateNotNullOrEmpty()]
        $Value=""

[Add-AMWorkflowLink.zip](https://github.com/automateps/AutomatePS/files/3073427/Add-AMWorkflowLink.zip)

**Comment by automateps** [comment]
I was able to reproduce this.
