### ISSUE TITLE
Format-AMUri is defaulting to US Date format in UK timezone

### ISSUE THREAD

**Issue by smistry-mangroup** [automateps/AutomatePS#27]
## Expected Behavior
PS C:\Users\smistry> Get-AMInstance -Status Running 

StartDateTime       EndDateTime         ConstructType ConstructName                                   AgentName    Status 
-------------       -----------         ------------- -------------                                   ---------    ------ 
24/01/2022 19:07:02 24/01/2022 19:07:11 Process       HeartbeatProcessAgent                           dlondbbfms71 Running

## Actual Behavior
Get-AMInstance
```
failure : Invalid format of parameter 'range_start'
At C:\Program Files\WindowsPowerShell\Modules\AutomatePS\5.1.0\Functions\Public\Invoke-AMRestMethod.ps1:103 char:13
+             throw "$($tempResult.Result) : $($tempResult.Info)"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (failure : Inval...r 'range_start':String) [], RuntimeException
    + FullyQualifiedErrorId : failure : Invalid format of parameter 'range_start'
```

## Steps to Reproduce the Problem

  1. Login to pc built on UK timezone
  2. Install AutomatePS
  3. Connect to Automate Instance
  4. Run Get-AMInstance

## Specifications

  - AutomatePS Version: 5.1.0
  - PowerShell Version: PSVersion 5.1.19041.1320 
  - Automate Version: 11.5.0.94

Note, I found a workaround was to update Format-AMUri to use GetDateTimeFormats()[77] to format the date in yyyy-MM-dd HH:mm:ss format e.g. 2022-01-25 15:13:25

example
```
    if ($PSBoundParameters.ContainsKey("RangeStart")) {
        $Parameters += "range_start=$($RangeStart.ToUniversalTime().GetDateTimeFormats()[77])"
    }
    if ($PSBoundParameters.ContainsKey("RangeEnd")) {
        $Parameters += "range_end=$($RangeEnd.ToUniversalTime().GetDateTimeFormats()[77])"
```

**Comment by davidseibel** [comment]
Thanks for sharing - good suggestion, but in my testing it seems to only work in PowerShell 5, not in PowerShell 7.  Here's a solution that should work for both versions.  Can you test with this and let me know if it works?  Thanks

``` PowerShell
if ($PSBoundParameters.ContainsKey("RangeStart")) {
    $Parameters += "range_start=$($RangeStart.ToUniversalTime().ToString((Get-Culture).DateTimeFormat.SortableDateTimePattern))"
}
if ($PSBoundParameters.ContainsKey("RangeEnd")) {
    $Parameters += "range_end=$($RangeEnd.ToUniversalTime().ToString((Get-Culture).DateTimeFormat.SortableDateTimePattern))"
}
```

**Comment by smistry-mangroup** [comment]
Hi David,

Thanks for picking this up! I’ve applied your code and it is working on my machine.

Format-AMUri.ps1

***@***.***

Date format is send to API correctly.

range_start=2022-02-07T09:00:41&range_end=2022-02-08T09:00:41

PS C:\Users\smistry> Get-AMInstance -Status Running -Verbose
VERBOSE: 08/02/2022 09:00:41 - Invoke-AMRestMethod started
VERBOSE: 08/02/2022 09:00:41 - Calling API (server: U-AP-ATM-M01)
VERBOSE: GET http://u-ap-atm-m01:9708/BPAManagement/instances/running/list?range_start=2022-02-07T09:00:41&range_end=2022-02-08T09:00:41&sort_field=StartDateTime with 0-byte payload
VERBOSE: received 135474-byte response of content type application/json; charset=utf-8
VERBOSE: 08/02/2022 09:00:44 - Converting from JSON (server: U-AP-ATM-M01)
VERBOSE: 08/02/2022 09:00:44 - Casting objects to correct type (server: U-AP-ATM-M01)
VERBOSE: 08/02/2022 09:00:44 - Invoke-AMRestMethod finished

Powershell version on my machine
PSVersion                      5.1.19041.1320

Is there is anything else you want me to check?

Thanks
Sunil Mistry

Platform Technology

***@***.******@***.***>

Tel +44 20 7144 3948





[logo]




Man Group plc | Riverbank House, 2 Swan Lane | London EC4R 3AD | United Kingdom
Registered in Jersey no. 127570
Visit us at: www.man.com<http://www.man.com>

P Man Group is a signatory to the UN-supported Principles for Responsible Investment
Please consider the environment before printing this email
